name: TALB236B
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.14.2,<3.15
  - jupyter>=1.1.1,<2
  - langdetect>=1.0.9,<2
  - chardet>=5.2.0,<6
  - ipywidgets>=8.1.8,<9
  - jupyterlab>=4.5.1,<5
  - jupyterlab-latex>=4.4.0,<5
