name: TALB236B
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.12
  - jupyter>=1.1.1,<2
  - langdetect>=1.0.9,<2
  - chardet>=5.2.0,<6
  - ipywidgets>=8.1.8,<9
  - jieba>=0.42.1,<0.43
  - jupyterlab>=4.5.1,<5
  - jupyterlab-latex>=4.4.0,<5
  - spacy>=3.8.11,<4
  - stanza>=1.11.0,<2
  - nltk>=3.9.2,<4
