[workspace]
authors = ["Alexandre Roulois <alexandre@roulois.fr>"]
channels = ["conda-forge"]
name = "TALB236B"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
python = ">=3.11,<3.12"
langdetect = ">=1.0.9,<2"
chardet = ">=5.2.0,<6"
ipywidgets = ">=8.1.8,<9"
jupyterlab = ">=4.5.4,<5"
jupyterlab-latex = ">=4.4.0,<5"
jieba = ">=0.42.1,<0.43"
spacy = ">=3.8.11,<4"
stanza = ">=1.11.0,<2"
nltk = ">=3.9.2,<4"
pip = ">=26.0.1,<27"
pandas = ">=3.0.1,<4"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.4.2,<3"
